### ISSUE TITLE
not work tts sonos

### ISSUE THREAD

**Issue by amgstone** [Talvish/home-assistant-blueprints#1]
`Logger: homeassistant.components.automation.svitlo_kukhnia_single
Source: helpers/script.py:409
Integration: Автоматизація ([documentation](https://www.home-assistant.io/integrations/automation), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+automation%22))
First occurred: 19:24:22 (6 occurrences)
Last logged: 19:51:17

Світло Кухня (single): Error executing script. Service not found for call_service at pos 2: Unable to find service tts.google_translate_say
Світло Кухня (single): Error executing script. Service not found for call_service at pos 2: Unable to find service tts.google_translate`

`alias: Світло Кухня (single)
description: ""
trigger:
  - platform: event
    event_type: mega.binary
    event_data:
      entity_id: binary_sensor.megad3_12
      type: single
condition: []
action:
  - service: light.toggle
    target:
      entity_id: light.dimmer_kitchen_led
    data:
      brightness: 255
      transition: 3
  - service: script.text_to_speech_on_sonos
    data:
      entity_id: media_player.stolovaia
      message: упс
      max_wait: 5
mode: single`

**Comment by Talvish** [comment]
Hi @amgstone , When the `script.text_to_speech_on_sonos` script was created from the blueprint, you were able specify the text-to-speech provider to use (and it defaults to Google Translate). From the above error it seems to indicate that either the Google Translate text-to-speech provider isn't installed in your Home Assistant or that it isn't setup to use the name `tts.google_translate`. Can you confirm?

**Comment by amgstone** [comment]
![Screenshot_2022-10-21-10-48-17-005_io homeassistant companion android](https://user-images.githubusercontent.com/63303107/197142265-0ba056bb-ef75-4336-8800-80b38020e001.jpg)
![Screenshot_2022-10-21-10-46-51-772_io homeassistant companion android](https://user-images.githubusercontent.com/63303107/197142285-0c5ebbec-f775-4971-8bf3-14824652a835.jpg)
![Screenshot_2022-10-21-10-46-19-821_io homeassistant companion android](https://user-images.githubusercontent.com/63303107/197142307-12196ef4-d752-43cf-9a4e-d945c769d8df.jpg)

**Comment by Talvish** [comment]
So looks like in your configuration you changed the Google Text-To-Speech to be called `google_say` . . . based on this:

![image](https://user-images.githubusercontent.com/694386/197329782-9b230c6e-ff1b-4b77-b8a4-95459fc4f8d0.png)

So when you create a script from my blueprint, use the `google_say` instead of the default of `googe_translate` . . . it is done on this screen you sent:

![image](https://user-images.githubusercontent.com/694386/197329832-0576c50d-bf10-4e1c-9bb0-83caab78a0f6.png)

**Comment by amgstone** [comment]
good!!!!
